
export const options = [
  { id: "web-development", label: "Web Development" },
  { id: "application", label: "Application" },
  { id: "business-software", label: "Business Software" },
  { id: "enterprise-sector", label: "Enterprise & Sector Specific" },
  { id: "ai-automation", label: "AI Automation" },
  { id: "branding-design", label: "Branding & Design" },
  { id: "others", label: "Others & Technical Services" },
];

export const servicesData = [
  {
    id: "web-development",
    label: "Web Development",
    services: [
      { id: "one-page-landing", name: "One-Page Landing Website", price: "150,000" },
      { id: "personal-portfolio", name: "Personal Portfolio Website", price: "₦200,000" },
      { id: "business-website", name: "Business Website (5–10 Pages)", price: "₦700,000" },
      { id: "corporate-website", name: "Corporate Website", price: "₦2,000,000" },
      { id: "church-website", name: "Church Website", price: "₦1,200,000" },
      { id: "school-website", name: "School Website", price: "₦2,000,000" },
      { id: "hospital-website", name: "Hospital Website", price: "₦4,000,000" },
      { id: "hotel-website", name: "Hotel Website", price: "₦3,200,000" },
      { id: "restaurant-website", name: "Restaurant Website", price: "₦2,000,000" },
      { id: "ngo-website", name: "NGO Website", price: "₦2,000,000" },
      { id: "real-estate-website", name: "Real Estate Website", price: "₦3,000,000" },
      { id: "news-blog", name: "News / Blog Website", price: "₦2,000,000" },
      { id: "job-portal", name: "Job Portal", price: "₦3,000,000" },
      { id: "e-commerce-website", name: "E-Commerce Website", price: "₦4,000,000" },
      { id: "multi-vendor-marketplace", name: "Multi-Vendor Marketplace", price: "₦5,000,000" },
      { id: "lms", name: "Learning Management System (LMS)", price: "₦4,500,000" },
      { id: "booking-system", name: "Booking & Reservation System", price: "₦3,000,000" },
      { id: "customer-portal", name: "Customer Portal", price: "₦3,500,000" },
      { id: "admin-dashboard", name: "Admin Dashboard", price: "₦2,500,000" },
      { id: "custom-web-app", name: "Custom Web Application", price: "From ₦4,000,000" },
    ],
  },
  {
    id: "application",
    label: "Application",
    services: [
      { id: "android-app", name: "Basic Android App", price: "₦1,500,000" },
      { id: "ios-app", name: "Basic iOS App", price: "₦2,000,000" },
      { id: "cross-platform-app", name: "Cross-Platform App (Flutter / React Native)", price: "₦3,000,000" },
      { id: "business-mobile-app", name: "Business Mobile App", price: "₦4,000,000" },
      { id: "ecommerce-mobile-app", name: "E-Commerce Mobile App", price: "₦4,500,000" },
      { id: "food-delivery-app", name: "Food Delivery App", price: "₦5,000,000" },
      { id: "ride-hailing-app", name: "Ride-Hailing App", price: "₦7,500,000" },
      { id: "hospital-mobile-app", name: "Hospital Mobile App", price: "₦4,500,000" },
      { id: "school-mobile-app", name: "School Mobile App", price: "₦3,500,000" },
      { id: "banking-fintech-app", name: "Banking / Fintech App", price: "From ₦12,000,000" },
      { id: "social-media-app", name: "Social Media App", price: "From ₦10,000,000" },
      { id: "streaming-app", name: "Streaming App", price: "From ₦8,000,000" },
    ],
  },
  {
    id: "business-software",
    label: "Business Software",
    services: [
      { id: "inventory-management", name: "Inventory Management System", price: "₦4,000,000" },
      { id: "pos-system", name: "Point of Sale (POS)", price: "₦6,000,000" },
      { id: "payroll-system", name: "Payroll Management System", price: "₦6,000,000" },
      { id: "hrms", name: "Human Resource Management System", price: "₦5,500,000" },
      { id: "school-management", name: "School Management System", price: "₦4,000,000" },
      { id: "hospital-management", name: "Hospital Management System", price: "₦5,000,000" },
      { id: "hotel-management", name: "Hotel Management System", price: "₦4,500,000" },
      { id: "restaurant-management", name: "Restaurant Management System", price: "₦3,500,000" },
      { id: "crm", name: "Customer Relationship Management (CRM)", price: "₦4,000,000" },
      { id: "erp", name: "Enterprise Resource Planning (ERP)", price: "From ₦12,000,000" },
      { id: "accounting-software", name: "Accounting Software", price: "₦4,500,000" },
      { id: "attendance-system", name: "Attendance System", price: "₦3,500,000" },
      { id: "visitor-management", name: "Visitor Management System", price: "₦2,500,000" },
      { id: "asset-management", name: "Asset Management System", price: "₦3,000,000" },
    ],
  },
  {
    id: "enterprise-sector",
    label: "Enterprise & Sector Specific",
    services: [
      { id: "government-portal", name: "Government Portal", price: "From ₦20,000,000" },
      { id: "banking-solution", name: "Banking Solution", price: "From ₦30,000,000" },
      { id: "insurance-platform", name: "Insurance Platform", price: "From ₦20,000,000" },
      { id: "logistics-management", name: "Logistics Management System", price: "From ₦7,500,000" },
      { id: "fleet-management", name: "Fleet Management System", price: "From ₦6,000,000" },
      { id: "cooperative-software", name: "Cooperative Management Software", price: "From ₦5,000,000" },
      { id: "sacco-software", name: "SACCO Management Software", price: "From ₦4,500,000" },
      { id: "voting-system", name: "Voting System", price: "From ₦25,000,000" },
      { id: "examination-portal", name: "Examination Portal", price: "From ₦6,000,000" },
    ],
  },
  {
    id: "ai-automation",
    label: "AI Automation",
    services: [
      { id: "ai-chatbot", name: "AI Chatbot", price: "₦1,500,000" },
      { id: "whatsapp-automation", name: "WhatsApp Automation", price: "₦1,200,000" },
      { id: "ai-customer-support", name: "AI Customer Support System", price: "₦2,500,000" },
      { id: "ai-document-processing", name: "AI Document Processing", price: "₦3,500,000" },
      { id: "business-process-automation", name: "Business Process Automation", price: "From ₦4,000,000" },
      { id: "ai-integration", name: "AI Integration", price: "From ₦2,500,000" },
    ],
  },
  {
    id: "branding-design",
    label: "Branding & Design",
    services: [
      { id: "logo-design", name: "Logo Design & Style Guide", price: "₦200,000" },
      { id: "brand-identity", name: "Full Brand Identity Package", price: "₦1,000,000" },
      { id: "ui-ux-design", name: "UI/UX Product Design (Figma)", price: "From ₦800,000" },
      { id: "pitch-deck-design", name: "Investor Pitch Deck Design", price: "₦500,000" },
      { id: "marketing-collateral", name: "Marketing & Print Assets Package", price: "₦350,000" },
    ],
  },
  {
    id: "others",
    label: "Others & Technical Services",
    services: [
      { id: "business-email", name: "Business Email Setup", price: "₦75,000" },
      { id: "domain-registration", name: "Domain Registration", price: "From ₦35,000 / year" },
      { id: "web-hosting", name: "Web Hosting", price: "From ₦120,000 / year" },
      { id: "ssl-setup", name: "SSL Certificate Setup", price: "₦50,000" },
      { id: "website-maintenance", name: "Website Maintenance", price: "From ₦150,000 / month" },
      { id: "seo-optimization", name: "SEO Optimization", price: "From ₦400,000" },
      { id: "speed-optimization", name: "Website Speed Optimization", price: "₦250,000" },
      { id: "software-consultation", name: "Software Consultation", price: "₦100,000 / hour" },
      { id: "bug-fixing", name: "Bug Fixing & Audits", price: "From ₦200,000" },
      { id: "api-integration", name: "API Integration", price: "From ₦400,000" },
      { id: "payment-gateway", name: "Payment Gateway Integration", price: "From ₦350,000" },
      { id: "cloud-deployment", name: "Cloud Deployment & DevOps", price: "From ₦350,000" },
      { id: "data-migration", name: "Data Migration", price: "From ₦300,000" },
    ],
  },
];